fastexcel/urls.py
from django.urls import path, include
from . import views
from .forms import  SignUpForm, LoginForm


urlpatterns = [
    path('', views.landing_page),
    path('accounts/register/', views.MyRegistrationView.as_view(form_class = SignUpForm), name='registration_register'),
    path('accounts/login/', views.MyLoginView.as_view() , name='auth_login'),
    path('accounts/', include('registration.backends.default.urls')),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('upload/', views.MyWizard.as_view(), name='upload'),
    path('quickbooks/callback/', views.QuickBooksCallbackView.as_view(), name='quickbooks_callback')
]

quickplugin/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fastexcel.urls')),

]

fastexcel/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.utils import timezone



# Create your models here.

#Customizing User model
class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, password, **extra_fields)

#custom model
class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    companyname = models.CharField(max_length=30)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['companyname']
 

    def __str__(self):
        return self.email



class UploadedFile(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    file = models.FileField(upload_to='uploads/')

fastexcel/forms.py
from django import forms
from registration.forms import RegistrationForm 
from django.contrib.auth.forms import AuthenticationForm




class LoginForm(AuthenticationForm):
    email = forms.EmailField(
        label='email',
        widget=forms.TextInput(attrs={'autofocus': True}),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'] = self.fields['email']
        del self.fields['email']


class SignUpForm(RegistrationForm):
  
    companyname = forms.CharField( label ='Company name', max_length=25, required=True)
    email = forms.EmailField(label ='Your email', max_length=25, required=True)
    password1 = forms.CharField(label ='password', max_length=25, required=True)
    password2 = forms.CharField(label ='Repeat your password', max_length=25, required=True)


    def save(self, commit=True):
        user = super().save(commit=False)
        user.companyname = self.cleaned_data['companyname']

        if commit:
            user.save()

        return user
    
class FileUploadForm(forms.Form):
    file = forms.FileField(required=True)

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(FileUploadForm, self).__init__(*args, **kwargs)
        self.user = user

    def clean_file(self):
        uploaded_file = self.cleaned_data.get('file')
        if uploaded_file:
            if not uploaded_file.name.lower().endswith(('.xls', '.xlsx')):
                raise forms.ValidationError("The uploaded file is not a valid Excel file.")
        return uploaded_file



class ColumnSelectionForm(forms.Form):
    def __init__(self, *args, **kwargs):
        columns = kwargs.pop('columns', [])
        super(ColumnSelectionForm, self).__init__(*args, **kwargs)

        for column in columns:
            self.fields[column] = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={'class': 'form-check form-check-my-class' , 'id': 'checkLabel'}))


class NumberForm(forms.Form):
    number_input = forms.IntegerField(label='Enter a Number')

fastexcel/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.conf import settings

from django.core.files.storage import FileSystemStorage
from django.core.files.base import ContentFile

from django.contrib.auth.views import LoginView
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from registration.backends.simple.views import RegistrationView
from multiprocessing import Pool
from formtools.wizard.views import SessionWizardView



from .forms import FileUploadForm, SignUpForm, LoginForm, ColumnSelectionForm, NumberForm
from .models import UploadedFile

from .datahandler import  extract_excel , get_column_data

from .qb import get_auth_url, get_access_token

from .pay import MpesaPay

import pandas as pd
import os




# Create your views here.


#class based views

class MyRegistrationView(RegistrationView):
    # logging.debug("Class initialised")
    template_name = 'registration.html'
    success_url = '/dashboard/'


class MyLoginView(LoginView):
    template_name = 'login.html'
    authentication_form = LoginForm

STEP_1 = 'file'
STEP_2 = 'columns'
STEP_3 = 'number'

class MyWizard(LoginRequiredMixin, SessionWizardView):
    steps = [STEP_1, STEP_2, STEP_3]
    
    form_list = [(STEP_1, FileUploadForm), (STEP_2, ColumnSelectionForm), (STEP_3, NumberForm)]
    template_name = 'uploadfile.html'
    # Wizard storage
    file_storage = FileSystemStorage(location='wizard/')

   
    def get_context_data(self, form, **kwargs):
        context = super().get_context_data(form=form, **kwargs)

        if self.steps.current == STEP_2:
            # Get the uploaded file from the previous step
            uploaded_file = self.get_cleaned_data_for_step(STEP_1)
            
            if uploaded_file:
                # Extract columns from the uploaded file and pass them to the ColumnSelectionForm
                columns = extract_excel(uploaded_file)  
                # Reinitialize the form with the columns data
                context['wizard']['form'] = ColumnSelectionForm(prefix=STEP_2, columns=columns)
                context['wizard']['text'] = "Please select the columns you want to export" 
                # print(context)
        return context
    
    def get(self, *args, **kwargs):
        # Check if the current step is 'columns'
        if self.steps.current == STEP_2:
            # Get the uploaded file from the previous step
            uploaded_file = self.get_cleaned_data_for_step(STEP_1)
            
            if uploaded_file:
                # Extract columns from the uploaded file and pass them to the ColumnSelectionForm
                columns = extract_excel(uploaded_file)
               
                # Render the 'columns' step with the updated form data
                return self.render(self.get_form(step=STEP_2, data=self.storage.get_step_data(STEP_2)))
        
        # If not at 'columns' step, proceed with the normal flow
        return super().get(*args, **kwargs)
    
    def post(self, *args, **kwargs):
        # Check if the current step is 'columns'
        print("Entering post method.")
        # Check if the form is being submitted
        print("Request method:", self.request.method)
        print("Form data:", self.request.POST)
        if self.steps.current == STEP_2:
            import pdb; pdb.set_trace()
            session_data = self.request.session
            print("Session data:", session_data)

            # Get the form instance for the current step
            step_data = self.storage.get_step_data(STEP_2)
            print("Step data:", step_data)
            form = self.get_form(step=STEP_2, data=step_data)

            print("Form instance:", form)

            # Check if the form is valid
            if form.is_valid():
                print("Form is valid. Redirecting to auth_url.")
                # Redirect to 'auth_url' after successful form submission
                auth_url = get_auth_url()
                return HttpResponseRedirect(auth_url)
            else:
                print("Form is not valid:", form.errors)
                # Render the form with errors
                return self.render(form)
                
              
        else:
            print("Not at 'columns' step")

        # If not at 'columns' step or form is not valid, proceed with the normal flow
        return super().post(*args, **kwargs)
    
   
    def done(self, form_list, form_dict,  **kwargs):
        # Get the uploaded file from the first form
        uploaded_file_data = form_list[0].cleaned_data.get('file')  # Assuming 'file' is the field name in your FileUploadForm

        if uploaded_file_data:
           
            user = self.request.user
            uploaded_file = UploadedFile(user=user, file=uploaded_file_data)
            # uploaded_file.file = uploaded_file_data  # Assign the uploaded file directly
            uploaded_file.save()

                      
            # Convert the generator into a list
            column_form_data = list(form_list[1].data.items())
            
            # Extract selected columns
            selected_columns = [key.split('-')[1] for key, value in column_form_data if value == 'on']
        

            # Process the uploaded file and selected columns
            columns_data = get_column_data(uploaded_file_data, selected_columns)
  

            #mpesa api at step 3 after redirect from quickbooks callbacks
            #payment = MpesaPay().stk_push(shortcode=None)

        return HttpResponseRedirect('dashboard')



#Quickbook callback 
class QuickBooksCallbackView(View):
    def get(self, request):
        # Handle the callback from QuickBooks
        authorization_code = request.GET.get('code')
        if authorization_code:
            # Authorization code is present, proceed with getting access token
            get_access_token(authorization_code)
            # Redirect back to the next step 3 of the wizard
            return redirect(reverse('upload', args=['number'])) 
            



#function based views
def landing_page(request):
    return render(request, 'index.html')


def dashboard(request): 
    #get the tottal number of uploaded files from the fastexcel_uploadfile db table based on the user of the request
    user = request.user
    total_files = UploadedFile.objects.filter(user=user).count()
    return render(request, 'charts.html' , {'total_files':total_files})

fastexcel/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Quick Plugin</title>
  <meta content="" name="description">
  <meta content="" name="keywords">



  <!-- Favicons -->
  <link href="https://think.ke/img/logo.png" rel="icon">
  <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">  
  <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Techie - v4.9.1
  * Template URL: https://bootstrapmade.com/techie-free-skin-bootstrap-3/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top ">
    <div class="container d-flex align-items-center justify-content-between">
      <h1 class="logo"><a href="/">Fast Excel</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo"><img src="static/img/logo.png" alt="" class="img-fluid"></a>-->

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="/">Home</a></li>
          <li><a class="nav-link scrollto" href="/#about">About</a></li>
     
          <li><a class="nav-link scrollto" href="/#contact">Contact</a></li>
          <li><a button type="button" class="nav-link scrollto" href="/accounts/login/">SignIn</a></li>
          <li><a button type="button" class="nav-link scrollto" href="/accounts/register/" >SignUp</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->
  {% if messages %}
  <div class="alert alert-danger">
      <ul>
          {% for message in messages %}
          <li>{{ message }}</li>
          {% endfor %}
      </ul>
  </div>
  {% endif %}

  {% block content %} {% endblock content%}


  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="{% static 'vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'vendor/aos/aos.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'js/main.js' %}"></script>

</body>

</html>

fastexcel/templates/base1.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Dashboard</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'newstatic/vendor/fontawesome-free/css/all.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'newstatic/css/sb-admin-2.css' %}" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <!-- <h1 class="logo"><a href="/">MetaBot</a></h1> -->
            <!-- <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <h1 class="logo"><a href="/">MetaBot</a></h1>
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
            </a> -->

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="/dashboard">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span></a>
            </li>

            

            <!-- Divider -->
            <!-- <hr class="sidebar-divider"> -->

            <!-- Heading -->
            <!-- <div class="sidebar-heading">
                Bot details
            </div> -->

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <li class="nav-item">
                    <a class="nav-link" href="/upload">
                        <i class="fas fa-fw fa-chart-area"></i>
                        <span>Export</span></a>
                </li>
             
            </li>

          
            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

           

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

  {% block content %} {% endblock content%}



        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal" style="background-color: forestgreen; border-color: forestgreen;">Cancel</button>
                    <a class="btn btn-primary" href="{% url 'auth_logout' %}" style="background-color: forestgreen; border-color: forestgreen;">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{%static 'newstatic/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{%static 'newstatic/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{%static 'newstatic/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{%static 'newstatic/js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{%static 'newstatic/vendor/chart.js/Chart.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{%static 'newstatic/js/demo/chart-area-demo.js' %}"></script>
    <script src="{%static 'newstatic/js/demo/chart-pie-demo.js' %}"></script>

</body>

</html>

fastexcel/templates/charts.html
{% extends "./index1.html" %}

{% load static %}


{% block content1 %}
    {{ block.super }} {# Include the content from index.html #}
  
     <!-- Begin Page Content -->
     <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <!-- <h1 class="h3 mb-0 text-gray-800">Dashboard</h1> -->
            <!-- <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"  ><i
                    class="fas fa-download fa-sm text-white-50"></i> Generate Report</a> -->
        </div>

        <!-- Content Row -->
        <div class="row">

            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-primary shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                    Files Exported</div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">{{ total_files}}</div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-calendar fa-2x text-gray-300"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

          
        </div>

    </div>
    
{% endblock %}

fastexcel/templates/index.html
{% extends "./base.html" %}
{% load static %}

{% block content%}

  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex align-items-center">

    <div class="container-fluid" data-aos="fade-up">
      <div class="row justify-content-center">
        <div class="col-xl-5 col-lg-6 pt-3 pt-lg-0 order-2 order-lg-1 d-flex flex-column justify-content-center">
          <h1>Fast Excel is a quick plug and export API that helps you transfer your data into your Quickbook without having to manually do it yourself.</h1>
          <!-- <h2>Fast Excel is a quick plug and export API that helps your data into your Quickbook without having to manually do it yourself.</h2> -->
          <div><a href="#about" class="btn-get-started scrollto">Get Started</a></div>
        </div>
    
      </div>
    </div>

  </section><!-- End Hero -->

  <main id="main">

    <!-- ======= About Section ======= -->
    <section id="about" class="about">
      <div class="container">

        
            <p class="fs-2">
              Simply export your excel sheet data into your quickbook. 
            </p>
            <div class="row">
              <div class="col-lg-3 col-md-6">
                <i class="bi bi-check-circle"></i> 
                <p class="fs-6">Create an account</p>
              </div>
    
              <div class="col-lg-3 col-md-6">
                <i class="bi bi-check-circle"></i> 
                <p class="fs-6">Upload a file.</p> 
              </div>
              <div class="col-lg-3 col-md-6">
                <i class="bi bi-check-circle"></i> 
                <p class="fs-6">Export to Quickbooks.</p>
              </div>
            </div>
            </div>

          

      </div>
    </section><!-- End About Section -->

  


  

    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact section-bg">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Contact</h2>
          <p>For Enquiries.</p>
        </div>

       
         <div class="row">
          <div class="col-lg-3 col-md-6">
            <div class="info-box  mb-4">
              <i class="bx bx-envelope"></i>
              <h3>Email Us</h3>
              <p>walalaneuman@gmail.com</p>
            </div>
          </div>

          <div class="col-lg-3 col-md-6">
            <div class="info-box  mb-4">
              <i class="bx bx-phone-call"></i>
              <h3>Call Us</h3>
              <p>+254 714 328 458</p>
            </div>
          </div>
        </div>
        </div>


    
    </section><!-- End Contact Section -->

 

  </main><!-- End #main -->

{% endblock content %}
  

fastexcel/templates/registration.html
{% extends "./base.html" %}

{% block content%}


  <main id="main">

    <section id="hero" class="d-flex align-items-center">
      <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-lg-12 col-xl-11">
            <div class="card text-black" style="border-radius: 25px;">
              <!-- <div class="card-body p-md-5"> -->
                <div class="row justify-content-center">
                  <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
    
                    <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign up</p>
                    
                    <!-- <form method="post" action="">
                      {% csrf_token %}

                      {{form.as_p}}
                   
                    <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                      <input type="submit" class="btn btn-primary btn-lg" value="Register" />
                    </div>


                    </form>  -->
                    
                    

    
                    <form  action="." method="post" class="mx-1 mx-md-4">
                      {% csrf_token %}
                      
                      

   
                      <div class="d-flex flex-row align-items-center mb-4">
                        <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                        <div class="form-outline flex-fill mb-0">
                          <label class="required" for="id_companyname" >Company Name</label>
                          <input type="text" name="companyname"  maxlength="25" autofocus required id="id_companyname", class="form-control custom-input">
                          
                          <!-- {{form.username}} -->
                        </div>
                      </div>
    
                      <div class="d-flex flex-row align-items-center mb-4">
                        <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                        <div class="form-outline flex-fill mb-0">
                          <label for="id_email" class="required">Your Email</label>
                          <input type="email" name="email"  maxlength="25" required id="id_email" class="form-control custom-input">
                          
                          <!-- {{form.email}} -->
                        </div>
                      </div>
    
                      <div class="d-flex flex-row align-items-center mb-4">
                        <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                        <div class="form-outline flex-fill mb-0">
                          <label for="id_password1" class="required">password</label>
                          <input type="text" name="password1"  maxlength="25" required id="id_password1" class="form-control custom-input">
                          
                          <!-- {{form.password1}} -->
                          {% if form.errors %}
                            <ul class="errorlist">
                              {% for field, errors in form.errors.items %}
                                {% for error in errors %}
                                  <li>{{ error }}</li>
                                {% endfor %}
                              {% endfor %}
                            </ul>
                          {% endif %}
                        </div>
                      </div>
                      
    
                      <div class="d-flex flex-row align-items-center mb-4">
                        <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                        <div class="form-outline flex-fill mb-0">
                          <label for="id_password2" class="required">Repeat your password</label>
                          <input type="text" name="password2"  maxlength="25" required id="id_password2" class="form-control custom-input">
                          
                          <!-- {{form.password2}} -->
                        </div>
                      </div>
    
                      <div class="form-check d-flex justify-content-center mb-5">
                        <!-- <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3c" name="value" />
                        <label class="form-check-label" for="form2Example3">
                          I agree all statements in <a href="#!">Terms of service</a>
                        </label> -->
                        <label class="form-check-label" for="form2Example3">
                          Already have an account? <a href="/accounts/login/">Sign In</a>
                        </label>
                      </div>
    
                      <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                      <input type="submit" class="btn btn-primary btn-lg " style="background-color: forestgreen; border-color: forestgreen;" value="Register" />
                      </div> 
    
                    </form>
    
                  </div>
                  <!-- <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
    
                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                      class="img-fluid" alt="Sample image">
    
                  </div> -->
                </div>
              <!-- </div> -->
            </div>
          </div>
        </div>
      </div>
    </section>
    


    
  </main><!-- End #main -->

{% endblock content%}